fix tests

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -50,9 +50,9 @@ jobs:
     steps:
       - uses: actions/checkout@v3
       - run: |
-          npm install
+          yarn install
       - run: |
-          npm run all
+          yarn all
 
   test-simple:
     runs-on: ubuntu-latest
@@ -89,8 +89,17 @@ jobs:
       - uses: actions/checkout@v3
 
       - uses: ./
+        id: test-failure
         with:
           if-file-not-found: error
+
+      - name: Verify Outcome
+        run: |
+          echo "Result: ${{ steps.test-failure.outcome }}"
+          if [[ "${{ steps.test-failure.outcome }}" != "failure" ]]; then
+            echo Expected failure
+            exit 1
+          fi
 
   test-quiet:
     runs-on: ubuntu-latest
@@ -113,7 +122,7 @@ jobs:
           path: .github/test-dir
           filenames: |
             .env
-            .env.test
+            test-override.env
 
       - name: Verify Export
         run: |
@@ -206,7 +215,7 @@ jobs:
           filenames: |
             test-cycle.env
 
-      - name: Verify Export
+      - name: Verify Outcome
         run: |
           echo "Result: ${{ steps.test-cycle.outcome }}"
           if [[ "${{ steps.test-cycle.outcome }}" != "failure" ]]; then
